[duan.package]
id = "examples.naval-combat.domains"
version = "0.1.0"
name = "Naval Combat Domains"

[duan.rust]
crate = "examples-naval-combat-domains"

[provides.domains]
"examples.naval-combat.domains.motion" = "schemas/motion.json"
"examples.naval-combat.domains.combat" = "schemas/combat.json"
"examples.naval-combat.domains.collision" = "schemas/collision.json"
