[duan.package]
id = "examples.free-fall.entities"
version = "0.1.0"
name = "Free Fall Entities"

[duan.rust]
crate = "examples-free-fall-entities"

[provides.entities]
"examples.free-fall.entities.ground" = "schemas/ground.json"
"examples.free-fall.entities.ball" = "schemas/ball.json"
