[duan.package]
id = "examples.naval-combat.entities"
version = "0.1.0"
name = "Naval Combat Entities"

[duan.rust]
crate = "examples-naval-combat-entities"

[provides.entities]
"examples.naval-combat.entities.ship" = "schemas/ship.json"
