[duan.package]
id = "examples.naval-combat.components"
version = "0.1.0"
name = "Naval Combat Components"

[duan.rust]
crate = "examples-naval-combat-components"

[provides.components]
"examples.naval-combat.components.faction" = "schemas/faction.json"
"examples.naval-combat.components.health" = "schemas/health.json"
"examples.naval-combat.components.radar" = "schemas/radar.json"
"examples.naval-combat.components.weapon" = "schemas/weapon.json"
