[duan.package]
id = "examples.naval-combat.reactions"
version = "0.1.0"
name = "Naval Combat Reactions"

[duan.rust]
crate = "examples-naval-combat-reactions"

[provides.reactions]
"examples.naval-combat.reactions.on-fire" = "schemas/on-fire.json"
"examples.naval-combat.reactions.on-hit" = "schemas/on-hit.json"
"examples.naval-combat.reactions.on-missile-expired" = "schemas/on-missile-expired.json"
"examples.naval-combat.reactions.on-ship-destroyed" = "schemas/on-ship-destroyed.json"
